new

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -133,60 +133,15 @@ jobs:
           path: |
             liberty-tools-intellij/build/reports/
 
-  build-status:
+  slack-notification:
     runs-on: ubuntu-latest
     needs: build
     if: always()
     steps:
-      - name: Check if artifact exists
-        id: check_artifact
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const artifactName = 'homework_pre';
-            const run_id = process.env.GITHUB_RUN_ID;
-            const owner = context.repo.owner;
-            const repo = context.repo.repo;
-            const artifacts = await github.request(`GET /repos/${owner}/${repo}/actions/runs/${run_id}/artifacts`);
-
-            const artifactExists = artifacts.data.artifacts.some(artifact => artifact.name === artifactName);
-
-            return { artifactExists: artifactExists ? 'true' : 'false' };
-
-      - name: Download artifact if it exists
-        if: steps.check_artifact.outputs.artifactExists == 'true'
-        uses: actions/download-artifact@v3
-        with:
-          name: homework_pre
-
-      - name: Fetch Build Status
-        id: status
+      - name: 'Slack Notification'
         run: |
-          status=""
-          if [ ${{ needs.build.result }} != "success" ]; then
-            status="failed"
-          else
-            status="succeeded"
-          fi
-          echo "status=$status" >> $GITHUB_OUTPUT
-
-          if [[ -f math-homework.txt ]]; then
-            echo "Appending to existing file"
-          else
-            echo "Creating new file"
-          fi
-
-          echo "value : $status" >> math-homework.txt  # Append the status to the file
-          cat math-homework.txt  # Display the contents of the file
+          STATUS=$([[ ${{ needs.build.result }} == "success" ]] && echo "succeeded" || echo "failed")
+          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"Workflow ${{ github.workflow }} triggered by branch ${{ github.ref }}. Build results: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}. Status: $STATUS\"}" $SLACK_WEBHOOK_URL
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_COPY }}
         shell: bash
-
-      - name: Print file contents
-        run: |
-          echo "Contents of math-homework.txt:"
-          cat math-homework.txt
-
-      - name: Upload math result for job 1
-        uses: actions/upload-artifact@v3
-        with:
-          name: homework_pre
-          path: math-homework.txt
